### ISSUE TITLE
Settings wont open, keybindings wont work.

### ISSUE THREAD

**Issue by BoKKeR** [gepd/uPiotMicroPythonTool#5]
### Operating system
Windows 10
### Description of problem
Cant use ctrl+alt+m shortcut, 

cant open upiot settings. "The settings file "res://Packages/upiot/Default.sublime-settings" could not be opened"
### Error(s) in ST Console? (View > Show Console)
reloading settings Packages/User/Preferences.sublime-settings
error: The settings file "res://Packages/upiot/Default.sublime-settings" could not be opened
### Steps to Reproduce
It worked at first, I installed python 3.6 and made a few reboots and after that it stopped working. I am not sure if this is a sublime text error or plugin error. I tried with a fresh install but it still wont work. ctrl+alt+p and ctrl+alt+o keybindings work.

**Comment by gepd** [comment]
It was a plugin problem, I've pushed a fix.
Run the option `Package Control: Upgrade/Overwrite All Packages` (ctrl + p) to get the last commit

**Comment by BoKKeR** [comment]
now I can open the settings but the keybinding ctrl+alt+m still won't work.

**Comment by gepd** [comment]
You may have a package overwriting that keybinding. 
Try replacing it from `Preferences > Package Settings > uPiot > Keybindings`

```json
{
        "keys": ["ctrl+alt+m"],
        "command": "show_overlay",
        "args": {
            "overlay": "command_palette", 
            "text": "UPIOT: "
        }
    }
```

If still not working go to `View > Show console` and paste the output here
